task_homepage:
    path:     /hello/{name}
    defaults: { _controller: TaskBundle:Default:index }
    
task_savetask:    
    path:     /savetask
    defaults: { _controller: TaskBundle:Default:savetask }
    
task_manage_task:    
    path:     /manageTasks/{type}/{id}
    defaults: { _controller: TaskBundle:Default:manageTasks }