task_homepage:
    path:     /hello/{name}
    defaults: { _controller: TaskBundle:Default:index }
    
task_updatetask:    
    path:     /updatetask
    defaults: { _controller: TaskBundle:Default:updatetask }
    
task_savetask:    
    path:     /savetask
    defaults: { _controller: TaskBundle:Default:savetask }
    
task_manage_task:    
    path:     /manageTasks/{type}/{id}
    defaults: { _controller: TaskBundle:Default:manageTasks }
    
task_get_task:    
    path:     /getTasks/{type}/{id}
    defaults: { _controller: TaskBundle:Default:getTasks }