contacts_contacts_homepage:
    path:     /hello/{name}
    defaults: { _controller: ContactsContactsBundle:Contacts:index }
   
contacts_contacts_managecontacts:
    path:     /contacts
    defaults: { _controller: ContactsContactsBundle:Contacts:managecontacts }
    
contacts_contacts_addcontact:
    path:     /addcontact
    defaults: { _controller: ContactsContactsBundle:Contacts:addcontact }

contacts_contacts_createcontact:
    path:     /createcontact
    defaults: { _controller: ContactsContactsBundle:Contacts:createcontact }

contacts_contacts_contactvalidate:
    path:     /contactvalidate
    defaults: { _controller: ContactsContactsBundle:Contacts:contactvalidate }

contacts_contacts_editcontactpage:
    path:     /editcontact/{id}
    defaults: { _controller: ContactsContactsBundle:Contacts:editcontactpage }
    
contacts_contacts_updatecontact:
    path:     /updatecontact
    defaults: { _controller: ContactsContactsBundle:Contacts:updatecontact }
    
contacts_contacts_activate:
   path:     /activate/{id}
   defaults: { _controller: ContactsContactsBundle:Contacts:activate }
   
contacts_contacts_deletecontact:
   path:     /deletecontact/{id}
   defaults: { _controller: ContactsContactsBundle:Contacts:deletecontact }
    
contacts_contacts_uploadcontact:
   path:     /uploadcontact
   defaults: { _controller: ContactsContactsBundle:Contacts:uploadcontact }
   
contacts_contacts_importcontacts:
   path:     /importcontacts
   defaults: { _controller: ContactsContactsBundle:Contacts:importcontacts }
   
contacts_contacts_contactavailability:
   path:     /contactavailability
   defaults: { _controller: ContactsContactsBundle:Contacts:contactavailability }

contacts_contacts_filteredopportunities:
   path:     /filteredopportunities/{name}
   defaults: { _controller: ContactsContactsBundle:Contacts:filteredopportunities }
   


    
    