opportunity_homepage:
    path:     /hello/{name}
    defaults: { _controller: OpportunityBundle:Default:index }

opportunity_addopportunity:
    path:     /addopportunity
    defaults: { _controller: OpportunityBundle:Default:addopportunity }
    
opportunity_addcontactopportunity:
    path:     /addcontactopportunity/{name}/{orgname}/{id}
    defaults: { _controller: OpportunityBundle:Default:addcontactopportunity }
    
opportunity_addcontactopportunityV2:
    path:     /addcontactopportunityV2/{id}
    defaults: { _controller: OpportunityBundle:Default:addcontactopportunityV2 }
    
opportunity_saveopportunity:
    path:     /saveopportunity
    defaults: { _controller: OpportunityBundle:Default:saveopportunity }
    
opportunity_editopportunity:
    path:     /editopportunity/{id}
    defaults: { _controller: OpportunityBundle:Default:editopportunity }
    
opportunity_editopportunityV2:
    path:     /editopportunityV2/{id}
    defaults: { _controller: OpportunityBundle:Default:editopportunityV2 }
    
opportunity_limitededitopportunity:
    path:     /limitededitopportunity/{id}
    defaults: { _controller: OpportunityBundle:Default:limitededitopportunity }
    
opportunity_activateopportunity:
    path:     /activateopportunity/{id}
    defaults: { _controller: OpportunityBundle:Default:activateopportunity }
    
opportunity_manageopportunity:
    path:     /manageopportunity
    defaults: { _controller: OpportunityBundle:Default:manageopportunity }
    
opportunity_manageopportunityV2:
    path:     /manageopportunityV2
    defaults: { _controller: OpportunityBundle:Default:manageopportunityV2 }
    
opportunity_opportunitycontactfilterV2:
    path:     /opportunitycontactfilterV2/{id}/{filter}
    defaults: { _controller: OpportunityBundle:Default:opportunitycontactfilterV2 }
    
opportunity_updateopportunity:
    path:     /updateopportunity
    defaults: { _controller: OpportunityBundle:Default:updateopportunity }
    
opportunity_deleteopportunity:
    path:     /deleteopportunity/{id}
    defaults: { _controller: OpportunityBundle:Default:deleteopportunity }
    
opportunity_table_data:
    path:     /opportunitytable/
    defaults: { _controller: OpportunityBundle:Default:getOpportunityTableData }
    